# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmojiResponseOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('+', ':thumbsup:'), ('-', ':thumbsdown:'), ('1', ':grinning:'), ('2', ':cry:'), ('3', ':laughing:'), ('4', ':scream:'), ('5', ':thinking:')], max_length=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='EmojiResponseOnResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('+', ':thumbsup:'), ('-', ':thumbsdown:'), ('1', ':grinning:'), ('2', ':cry:'), ('3', ':laughing:'), ('4', ':scream:'), ('5', ':thinking:')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('is_private', models.BooleanField()),
                ('is_draft', models.BooleanField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.Prompt')),
            ],
        ),
        migrations.CreateModel(
            name='TroveObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trove_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=50)),
                ('last_login', models.DateField()),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.UserAccount'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='trove_objects',
            field=models.ManyToManyField(to='storytrove.TroveObject'),
        ),
        migrations.AddField(
            model_name='emojiresponseonresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.Response'),
        ),
        migrations.AddField(
            model_name='emojiresponseonresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.UserAccount'),
        ),
        migrations.AddField(
            model_name='emojiresponseoncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.UserAccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.Response'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytrove.UserAccount'),
        ),
    ]
