# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytrove', '0002_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ManyToManyField(blank=True, to='storytrove.UserAccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
