#%RAML 1.0
title: StoryTrove
version: v1
baseUri: http://deco1800-111.uqcloud.net/api/
/user:
    /login:
    /logout:
    /check:
    /edit:
/prompts:
    description: Get a list of prompts with associated details. Defaults to a selection of prompts from multiple tags.
    get:
        queryParameters:
            tags:
              description: comma separated list of tags to search on
              type: string
              required: false
            reactions:
              description: comma separated list of reactions to search on
              type: string
              required: false
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": {
                                    "results": [],
                                }
                            }
/stories:
    description: |
        Get a list of stories sorted by newest first.
        Optionally filter results with query parameters.
    get:
        queryParameters:
            tags:
              description: comma separated list of tags to filter by
              type: string
            reactions:
              description: comma separated list of reactions to filter by
              type: string
            author:
              description: author username to filter results
              type: string
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": {
                                    "results": [],
                                }
                            }
/comments:
    /{resource_id}:
        description: Get a list of comments with associated metadata for the given resource id
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true,
                                    "data": {
                                        "results": [],
                                    }
                                }
/voteup:
    /{resource_id}:
        description: Add an upvote to the given resource
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true
                                }
/votedown:
    /{resource_id}:
        description: Add a downvote to the given resource
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true
                                }
/react:
    /{resource_id}:
        description: Add a reaction to the given resource
        get:
            queryParameters:
                reaction:
                    description: Reaction name to add
                    type: string
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true
                                }
/comment:
    /{resource_id}:
        description: Add a comment to the given resource
        get:
            queryParameters:
                message:
                  description: Full unformatted message text
                  type: string
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true
                                }
/prompt:
    /{resource_id}:
        description: |
            Get details of a particular prompt including image urls,
            story metadata, reactions etc.
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true,
                                    "prompt": {
                                        "works": []
                                    }
                                }

/story:
    /{resource_id}:
        description: |
            Get details of a particular story, including the story text, author,
            votes, reactions and comment metadata.
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "success": true,
                                    "story": {
                                        "resource_id": "1Q32udk2OE",
                                        "url": "https://deco1800-111.uqcloud.net/story/1Q32udk2OE",
                                        "prompt_id": "23423442342",
                                        "title": "Hello, storytrove!",
                                        "body": "Once upon a trove...",
                                        "votes": 9,
                                        "reactions": [
                                            ":smile:": 3,
                                            ":heart:": 1
                                        ]
                                    }
                                }
